### ISSUE TITLE
License

### ISSUE THREAD

**Issue by m4ttr4ymond** [dbarenholz/obsidian-plaintext#12]
I would like to fork this repository for an obsidian plugin that I'm working on. Would you be able to add a software license so that I can make sure that I follow attribution best-practices?

**Comment by m4ttr4ymond** [comment]
I found the following line in `package.json`, so I think this is under the MIT license:
```
"license": "MIT",
```
 However, I'll wait until I hear back from @dbarenholz to be sure.

**Comment by dbarenholz** [comment]
Apologies for the delay @m4ttr4ymond - you're free to fork and use as you see fit according to MIT license!
