### ISSUE TITLE
Syntax coloring for code files

### ISSUE THREAD

**Issue by vguillet** [dbarenholz/obsidian-plaintext#14]
Hey! Love the plugin so far! I was wondering about the following. If it is possible to open any file extension as plain text, would it be possible to have syntax colouring for code scripts (based on file extension)? This would really go a long way toward improving the usage of Obsidian for programming-oriented notes/documentation and could be the first step to turning Obsidian into a basic IDE!

**Comment by dbarenholz** [comment]
Identical to https://github.com/dbarenholz/obsidian-plaintext/issues/10 - closing this issue!
