### ISSUE TITLE
Allow linking to and embedding plaintext files.

### ISSUE THREAD

**Issue by dbarenholz** [dbarenholz/obsidian-plaintext#3]
When you add a particular extension to the list of plaintext extensions, said file cannot yet be linked to. This would be a very nice to have as to further integrate the plugin into Obsidian.

Even better would be if we can embed the file using the default `![[file.ext]]` syntax.

**Comment by dbarenholz** [comment]
Not really possible. See <https://github.com/deathau/cooklang-obsidian/discussions/10>.

The only way to link to a file natively is if it's a markdown file. The way that Excalidraw fixes this, is by having `file.excalidraw.md` files, which are as you can see normal markdown files. Doing the same for a plaintext plugin kind of defeats the idea of the plugin: Anyone can rename their `file.ext` to `file.ext.md` and it will show up in Obsidian.

The 'workaround' is to have each file doubled (so, _both_ `file.ext` and `file.ext.md`), and code in place to make sure they're kept in sync. This seems like a terrible idea for various reasons, so I won't be doing this.

**Comment by Trikzon** [comment]
It's a shame that this isn't feasible. Wanting to embed `*.py` files was the reason I found this plugin.
