### ISSUE TITLE
Enable for mobile?

### ISSUE THREAD

**Issue by loopernow** [dbarenholz/obsidian-plaintext#4]
Could this plugin be enabled for mobile devices? It is not allowed for Obsidian on my Android phone.

**Comment by colintedford** [comment]
Would definitely use this (on iOS).

**Comment by dbarenholz** [comment]
I'm happy to set mobile to true, but I can't really test it due to time. That's why all my plugins are by default not enabled on mobile.

Will change!

**Comment by pm64** [comment]
After modifying the manifest, I thoroughly tested this (quite excellent) plug-in on numerous browsers on both iOS and Android, in both handset and tablet form factors, and did not observe any unexpected behavior.

**Comment by dbarenholz** [comment]
Much appreciated for testing - currently on vacation but I'll set a reminder to update it once I'm back home. Apologies for all the delays, I forgot this existed 🙃

**Comment by dbarenholz** [comment]
Enabled for mobile in 0.2.0!
