### ISSUE TITLE
Ability to create new files inside obsidian

### ISSUE THREAD

**Issue by elias-sundqvist** [dbarenholz/obsidian-plaintext#7]
Obsidian assumes that new notes are `.md` files. 
It would be great to have a button in the obsidian file explorer/context menu to create new plaintext files.

**Comment by dbarenholz** [comment]
@elias-sundqvist Any ideas on how to best implement a method that is mobile-friendly that creates a new file? Button (and soon command) has already been made, but struggling with implementation.

**Comment by elias-sundqvist** [comment]
Not sure if I understood your question, but you can create files in obsidian by doing `await app.vault.create('path/to/file.ext', "")`

**Comment by dbarenholz** [comment]
> Not sure if I understood your question, but you can create files in obsidian by doing `await app.vault.create('path/to/file.ext', "")`

Implemented in 2 ways: right click on a folder allows you to create a new plaintext file in the selected folder, and there's also a command available that will make one and put it in the root directory of the vault! Will be in version 1.0.0 (which also uses CM6 in stead of CM5)

**Comment by elias-sundqvist** [comment]
Great! Thanks :)

**Comment by holroy** [comment]
How, if it does, will this cope with guys like me wanting to create a `.js` or `.css` or `.py` file?

**Comment by dbarenholz** [comment]
@elias-sundqvist This is now updated - will make the release in a second (after going through the issues that I fixed)

@holroy Please create a separate issue for this so I can properly track it :)
